---
title: "Integration of Axin2 and P10 suture"
subtitle: "Fig.S13"
author: "Zhirui Jiang"
date: "2023-06-22"
output: html_document
---

# load library
```{r}
library(Seurat)
library(SeuratDisk)
library(SeuratWrappers)
library(patchwork)
devtools::install_github("immunogenomics/harmony")
library(harmony)
library(rliger)
library(reshape2)
library(RColorBrewer)
library(dplyr)
library(data.table)
library(magrittr)
```

# Load datasets
```{r}
suture.combined <- readRDS("suture_combined.rds")
Axin2 <- readRDS("Axin2+_scRNA-seq_combined.rds")

# make a list and normalize for each object:
wb_list <- list()
wb_list[["suture"]]   <- suture.combined
wb_list[["Axin2"]]  <- Axin2

for (i in 1:length(wb_list)) {
  wb_list[[i]] <- NormalizeData(wb_list[[i]], verbose = F)
  wb_list[[i]] <- FindVariableFeatures(wb_list[[i]], selection.method = "vst", nfeatures = 2000, verbose = F)
}

# integration in two steps
wb_anchors <- FindIntegrationAnchors(object.list = wb_list, dims = 1:30)
wb_seurat  <- IntegrateData(anchorset = wb_anchors, dims = 1:30)

rm(wb_list)
rm(wb_anchors)

# Processing and visulaiztion
DefaultAssay(wb_seurat) <- "RNA"
wb_seurat <- NormalizeData(wb_seurat, verbose = F)
wb_seurat <- FindVariableFeatures(wb_seurat, selection.method = "vst", nfeatures = 2000, verbose = F)
wb_seurat <- ScaleData(wb_seurat, verbose = F)
wb_seurat <- RunPCA(wb_seurat, npcs = 30, verbose = F)
wb_seurat <- RunUMAP(wb_seurat, reduction = "pca", dims = 1:30, verbose = F)
wb_seurat <- RunTSNE(wb_seurat, reduction = "pca", dims = 1:30, verbose = F)

# UMAP plot before integration
DimPlot(wb_seurat, reduction = "umap") + plot_annotation(title = "Axin2+ to mouse suture before integration")
DimPlot(wb_seurat, reduction = "tsne") + plot_annotation(title = "Axin2+ to mouse suture before integration")

# Integrated dataset
DefaultAssay(wb_seurat) <- "integrated"
wb_seurat <- ScaleData(wb_seurat, verbose = F)
wb_seurat <- RunPCA(wb_seurat, npcs = 30, verbose = F)
wb_seurat <- RunUMAP(wb_seurat, reduction = "pca", dims = 1:30, verbose = F)

# UMAP plot after integration
DimPlot(wb_seurat, reduction = "umap") + plot_annotation(title = "Axin2+ to mouse suture, after integration")
DimPlot(wb_seurat, reduction = "tsne") + plot_annotation(title = "Axin2+ to mouse suture, after integration")

DimPlot(wb_seurat, reduction = "umap", group.by = "orig.ident", pt.size = .1, split.by = 'orig.ident') + NoLegend()

# integrated matrix and look how clusters are distributed between the two sets
wb_seurat <- FindNeighbors(wb_seurat, dims = 1:30, k.param = 10, verbose = F)
wb_seurat <- FindClusters(wb_seurat, verbose = F)
Idents(wb_seurat)="seurat_clusters"
DimPlot(wb_seurat,label = T, cols = c()) + NoLegend()

# cluster composition
count_table <- table(wb_seurat@meta.data$seurat_clusters, wb_seurat@meta.data$orig.ident)
count_table

saveRDS(wb_seurat, file = "Axin2_Holmes_integration.rds")
```


# Subset
```{r}
wb_subset<-subset(x = wb_seurat, idents = c("2","3","4","5","7","8","9","10",
                                             "11","12","13","14","16","17","18",
                                             "19","20","21","22","23","24","25",
                                             "26","27","28","29","30","31"),
                  invert = TRUE)

# Re-cluster subset
DefaultAssay(wb_subset) <- "integrated"
wb_subset <- FindNeighbors(wb_subset, dims = 1:30, k.param = 10, verbose = F)
wb_subset.t <- FindClusters(wb_subset, verbose = F, resolution = 0.2)

# Visualization
DimPlot(wb_subset.t,reduction ="umap",group.by = "orig.ident", pt.size = 0.5)
DimPlot(wb_subset.t,reduction="umap", label = TRUE, pt.size = 0.5)

new.cluster.ids<- c("SuSC","OB","OP","COP") 
names(x=new.cluster.ids) <-levels(x=wb_subset.t)
wb_subset.t<-RenameIdents(object = wb_subset.t,new.cluster.ids)
DimPlot(object = wb_subset.t, reduction = 'umap',label = TRUE, pt.size = 0.5, label.size = 4)+ NoLegend()+FontSize(x.text = 12,y.text = 12,x.title=14,y.title = 14)


# Identify gene markers per cluster
DefaultAssay(wb_subset.t) <- "RNA"
all_markers <-FindAllMarkers(wb_subset.t,
                             only.pos = TRUE,
                             min.pct =  0.25, 
                             min.diff.pct = 0.25)



# cluster composition
count_table <- table(wb_subset.t@meta.data$seurat_clusters, wb_subset.t@meta.data$orig.ident)
count_table

# Dot plot
DefaultAssay(wb_subset.t) <- "integrated"
wb_subset.t@active.ident <- factor(wb_subset.t@active.ident,
                                 levels=c("SuSC","OP","OB","COP"))

features <- c("Sparc","Spp1","Mmp13","Alpl","Twist1","Msx1","Mpo","Elane")

DotPlot(wb_subset.t, features = features) + RotatedAxis()+
  theme(axis.text=element_text(size=20),
        axis.title=element_text(size=20))

DefaultAssay(wb_subset.t)<-"RNA"
VlnPlot(object = wb_subset.t, features = c("Lrig3"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Thy1"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Msx2"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Erg"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Msx1"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Sparc"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Mmp13"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Bglap"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Spp1"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Sp7"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Alpl"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Ibsp"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Bmper"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Acvrl1"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Rab23"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Six2"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Gli1"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Ctsk"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Prrx1"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Mpo"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Elane"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Ptprc"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Mmp9"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Twist1"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Grem1"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Lepr"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Pthlh"), ncol=1,pt.size = 0)
VlnPlot(object = wb_subset.t, features = c("Erg"), ncol=1,pt.size = 0)
```

